name: build-and-deploy

on:
  push:
    branches:
      - main   # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.aaradhyvijaywat }}
          password: ${{ secrets.dckr_pat_NVbk5ErUdu69DAlg9YF3lHYRWKI }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-image-name:latest
